spring:
  application:
    name: geovision-backend

  datasource:
    url: jdbc:postgresql://db.pwbjvbdsqzvmveodkllu.supabase.co:5432/postgres
    username: postgres
    password: SatyajitDB@1205

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 105MB

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

geovision:
  upload:
    base-dir: uploads
    max-file-size: 104857600
